openapi: 3.0.0
info:
  version: 1.0.0
  title: Fifth Cuccc Services v2
  description: Fifth Cuccc Services v2

paths:
  /greeting/:
    $ref: './greeting-services.yaml#/greeting'
  /greeting/{helloName}:
    $ref: './greeting-services.yaml#/hello'
  /healthcheck:
    $ref: './move-services.yaml#/healthcheck'
  /move/all:
    $ref: './move-services.yaml#/moveAll'
  /move:
    $ref: './move-services.yaml#/move'
  /move/{id}:
    $ref: './move-services.yaml#/moveId'
  /move/{id}/rate:
    $ref: './move-services.yaml#/moveRateById'
