openapi: 3.0.0
info:
  version: 1.0.0
  title: Fifth Cucc Services v2
  description: Fifth Cucc Services v2

#security:
#  - bearerAuth: []

healthcheck:
  get:
    tags:
      - 'HealthCheckService'
    operationId: healthCheck
    description: 'Health Check'
    responses:
      200:
        description: 'Success'

moveAll:
  get:
    tags:
      - 'MoveService'
    operationId: findAll
    description: 'All Moves'
    responses:
      200:
        description: 'Success'
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Move'
      500:
        description: 'Internal server error'

moveId:
  get:
    tags:
      - 'MoveService'
    operationId: getById
    description: 'return a Move by id'
    produces:
      - application/json
    parameters:
      - name: id
        in: path
        description: 'Id of Move to return'
        required: true
        schema:
          type: integer
    responses:
      200:
        description: 'Success'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Move'
      500:
        description: 'Internal server error'
  put:
    tags:
      - 'MoveService'
    description: 'Update Move'
    operationId: update
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: path
        name: id
        description: 'Id of product to return'
        required: true
        schema:
          type: integer
    requestBody:
      $ref: '#/components/requestBodies/MoveBody'
    responses:
      200:
        description: Success
        headers:
          signature:
            type: string
            description: 'Service message'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Move'
      500:
        description: 'Internal server error'
  delete:
    tags:
      - 'MoveService'
    operationId: delete
    description: 'delete a Move by id'
    parameters:
#      - in: header
#        name: Authorization
#        required: true
#        schema:
#          type: string
      - in: path
        name: id
        description: 'Id of Move to return'
        required: true
        schema:
          type: integer
    responses:
      200:
        description: 'Success'
      400:
        description: 'Invalid ID supplied'
      404:
        description: 'Move not found'

move:
  post:
    tags:
      - 'MoveService'
    description: 'Add a new Move to the store'
    operationId: create
    consumes:
      - application/json
    produces:
      - application/json
    requestBody:
      $ref: '#/components/requestBodies/MoveBody'
    responses:
      200:
        description: "Success"
        headers:
          signature:
            type: string
            description: 'Service message'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Move'

      405:
        description: 'Invalid input'
      500:
        description: 'Internal server error'

moveRateById:
  put:
    tags:
      - 'MoveService'
    description: 'Update Move Rate'
    operationId: updateMoveRateById
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: path
        name: id
        description: 'Id of Move to return'
        required: true
        schema:
          type: integer
    requestBody:
      $ref: '#/components/requestBodies/RateBody'
    responses:
      200:
        description: Success
        headers:
          signature:
            type: string
            description: 'Service message'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Move'
      500:
        description: 'Internal server error'

components:
  schemas:
    Move:
      description: 'Move model'
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        rate:
          type: integer

    Rate:
      description: 'RateObject for Move model'
      properties:
        rate:
          type: integer
      required:
        - rate

  requestBodies:
    MoveBody:
      description: A JSON object containing Move information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Move'
    RateBody:
      description: A JSON object containing Move information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Rate'

